### ISSUE TITLE
SIGSEGV: segmentation while running against twitter.com

### ISSUE THREAD

**Issue by crequena-babbel** [mrls/lnchk#1]
The current code is failing as follows:
> $ ./lnchk https://www.twitter.com/babbel
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1239b7c]
> 
> goroutine 119 [running]:
> main.main.func1.1(0xc420118000, 0xc42049b2c0, 0xc42029ec90, 0xc420141480, 0x7f)
> 	/Users/crequena/tmp/MAURO/lnchk/lnchk.go:141 +0x10c
> created by main.main.func1
> 	/Users/crequena/tmp/MAURO/lnchk/lnchk.go:135 +0xe7
>

**Comment by mrls** [comment]
Thanks @crequena-babbel I've modified the code to handle such issues now
